version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ejercicio_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data_ejercicio:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - ejercicio_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: ejercicio_api
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ejercicio_network
    volumes:
      - ./src:/app
      - /app/node_modules
    command: npm run dev

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ejercicio_pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - ejercicio_network

volumes:
  pg_data_ejercicio:

networks:
  ejercicio_network:
    driver: bridge